#!/usr/bin/env bash
# agentsync profile — manage config-home profiles (work/personal variants).
#
#   agentsync profile add <name> [--tools a,b] [--adopt] [--yes]
#   agentsync profile list
#   agentsync profile remove <name> [--yes]
#
# A profile scaffolds one thin variant tool per base tool (.ai/src/tools/<base>-<name>.yaml,
# config-home dests via profile_rewrite_dest), an overlay dir (.ai/profiles/<name>/src),
# and a `profiles:` entry in agent_sync.yaml. `sync` then materialises each
# variant into its own config-home directory with base ⊕ profile content.

_profile_prepare_context() {
    local project_dir
    project_dir="${AGENTSYNC_REPO_ROOT:-$(pwd)}"
    project_dir="$(cd "$project_dir" && pwd)"
    REPO_ROOT="$project_dir"
    REPO_ROOT_CANONICAL="$(cd -P "$project_dir" && pwd)"

    local system_dir
    system_dir=$(resolve_system_dir 2>/dev/null) || {
        echo "$(_red "Error"): AgentSync engine not found." >&2
        exit 2
    }
    DEFAULT_REPO_ROOT="$(cd "$system_dir/.." && pwd)"

    PROJECT_CONFIG_PATH=""
    if [[ -f "$project_dir/.ai/agent_sync.yaml" ]]; then
        PROJECT_CONFIG_PATH="$project_dir/.ai/agent_sync.yaml"
    elif [[ -f "$project_dir/agent_sync.yaml" ]]; then
        PROJECT_CONFIG_PATH="$project_dir/agent_sync.yaml"
    fi

    export REPO_ROOT REPO_ROOT_CANONICAL DEFAULT_REPO_ROOT PROJECT_CONFIG_PATH
}

# Default config-home directory name for a base tool in a profile: ".<base>-<name>".
_profile_home_dir() {
    local base_tool="$1"
    local name="$2"
    echo ".${base_tool}-${name}"
}

# Emit the `targets:` block for a variant: every base resource that declares a
# dest, rewritten into the config-home layout. Echoes nothing if the base
# declares no dests (e.g. an unknown tool).
_profile_variant_targets() {
    local base_tool="$1"
    local home="$2"
    local emitted=false
    local key raw rewritten
    for key in agents rules skills commands subagents settings mcp hooks; do
        raw=$(get_tool_value "$base_tool" "targets.$key.dest")
        [[ -z "$raw" ]] && continue
        if [[ "$emitted" == false ]]; then
            printf 'targets:\n'
            emitted=true
        fi
        rewritten=$(profile_rewrite_dest "$raw" "$home")
        printf '  %s:\n    dest: "%s"\n' "$key" "$rewritten"
    done
}

# Write the thin variant tool YAML for <base_tool> under <variant_name>.
_profile_write_variant() {
    local base_tool="$1"
    local variant_name="$2"
    local home="$3"
    local profile="$4"

    local user_file
    user_file=$(tool_resolver_user_file "$variant_name")
    mkdir -p "$(dirname "$user_file")"

    local label
    label="$(tool_display_name "$base_tool") ($profile)"

    {
        printf '# %s — AgentSync profile variant (profile: %s).\n' "$label" "$profile"
        printf '# Generated by `agentsync profile add`. Inherits unset fields from base `%s`.\n' "$base_tool"
        printf 'base: %s\n' "$base_tool"
        printf 'name: "%s"\n' "$label"
        printf 'profile_home: "%s"\n' "$home"
        _profile_variant_targets "$base_tool" "$home"
    } > "$user_file"

    echo "$user_file"
}

# Insert a text block immediately after line <after> of <file>.
# Pipes through _yaml_atomic_write (yaml_edit.sh) so the writer's exit status —
# not the read loop's EOF status — governs success under set -e.
_profile_insert_after_line() {
    local file="$1"
    local after="$2"
    local block="$3"
    local lineno=0
    {
        while IFS= read -r line || [[ -n "$line" ]]; do
            ((lineno++)) || true
            printf '%s\n' "$line"
            if [[ $lineno -eq $after ]]; then
                printf '%s' "$block"
            fi
        done < "$file"
    } | _yaml_atomic_write "$file"
}

# Register the profile in agent_sync.yaml: create the `profiles:` block, or
# insert a new child under an existing one. <variants> is space-separated.
_profile_register() {
    local name="$1"
    local overlay_rel="$2"
    shift 2
    local -a variants=("$@")

    local cfg="$PROJECT_CONFIG_PATH"
    [[ -n "$cfg" ]] || { echo "$(_red "Error"): no agent_sync.yaml found." >&2; return 1; }

    local child=""
    child+="  ${name}:"$'\n'
    child+="    overlay: \"${overlay_rel}\""$'\n'
    child+="    active: true"$'\n'
    child+="    tools: [$(IFS=', '; echo "${variants[*]}")]"$'\n'

    local profiles_line
    profiles_line=$(_yaml_find_key_line "$cfg" "profiles")
    if [[ -z "$profiles_line" ]]; then
        printf '\nprofiles:\n%s' "$child" >> "$cfg"
    else
        local lineno
        lineno=$(echo "$profiles_line" | awk '{print $1}')
        _profile_insert_after_line "$cfg" "$lineno" "$child"
    fi
}

# Copy existing config-home content into the profile overlay / variant payload
# dir, reversing profile_rewrite_dest. Best-effort: only copies what exists.
_profile_adopt_home() {
    local variant_name="$1"
    local home="$2"
    local overlay_src="$3"

    local home_abs="$REPO_ROOT/$home"
    [[ -d "$home_abs" ]] || return 0

    local item
    for item in rules skills commands agents; do
        [[ -d "$home_abs/$item" ]] || continue
        mkdir -p "$overlay_src/$item"
        cp -R "$home_abs/$item/." "$overlay_src/$item/" 2>/dev/null || true
    done
    # Agents/identity file: CLAUDE.md, AGENTS.md, GEMINI.md, …
    local f
    for f in "$home_abs"/*.md; do
        [[ -f "$f" ]] || continue
        cp "$f" "$overlay_src/AGENTS.md"
        break
    done
    # Payloads: settings/mcp/hooks into the per-variant override dir.
    local payload_dir="$REPO_ROOT/.ai/src/tools/$variant_name"
    [[ -f "$home_abs/.mcp.json" ]]      && { mkdir -p "$payload_dir"; cp "$home_abs/.mcp.json" "$payload_dir/mcp.json"; }
    [[ -f "$home_abs/settings.json" ]]  && { mkdir -p "$payload_dir"; cp "$home_abs/settings.json" "$payload_dir/settings.json"; }
    [[ -f "$home_abs/hooks.json" ]]     && { mkdir -p "$payload_dir"; cp "$home_abs/hooks.json" "$payload_dir/hooks.json"; }
    return 0
}

# ── add ─────────────────────────────────────────────────────────────────────

_profile_add() {
    local name=""
    local tools_csv=""
    local do_adopt=false
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --tools) tools_csv="${2:-}"; shift 2 ;;
            --adopt) do_adopt=true; shift ;;
            --yes|-y) shift ;;
            -*) echo "$(_red "Error"): unknown flag: $1" >&2; return 2 ;;
            *) if [[ -z "$name" ]]; then name="$1"; shift; else echo "$(_red "Error"): too many arguments." >&2; return 2; fi ;;
        esac
    done

    if [[ -z "$name" ]]; then
        echo "$(_red "Error"): agentsync profile add <name> [--tools a,b] [--adopt]" >&2
        return 2
    fi
    if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        echo "$(_red "Error"): profile name must be [a-zA-Z0-9_-]." >&2
        return 2
    fi

    _profile_prepare_context

    if [[ -z "$PROJECT_CONFIG_PATH" ]]; then
        echo "$(_red "Error"): no agent_sync.yaml — run 'agentsync init' first." >&2
        return 1
    fi
    if [[ -n "$(_yaml_find_key_line "$PROJECT_CONFIG_PATH" "profiles.$name")" ]]; then
        echo "$(_yellow "Profile '$name' already exists") in $PROJECT_CONFIG_PATH" >&2
        return 1
    fi

    # Base tools: explicit --tools, else the personal enabled set.
    local -a base_tools=()
    local t
    if [[ -n "$tools_csv" ]]; then
        local IFS=','
        for t in $tools_csv; do [[ -n "$t" ]] && base_tools+=("$t"); done
    else
        while IFS= read -r t; do [[ -n "$t" ]] && base_tools+=("$t"); done < <(list_configured_enabled_tools)
    fi
    if [[ ${#base_tools[@]} -eq 0 ]]; then
        echo "$(_red "Error"): no base tools — enable tools first or pass --tools." >&2
        return 1
    fi

    local overlay_rel=".ai/profiles/$name"
    local overlay_src="$REPO_ROOT/$overlay_rel/src"
    mkdir -p "$overlay_src/rules" "$overlay_src/skills"

    echo ""
    _bold "  Creating profile '$name'"; echo ""

    local -a variants=()
    local bt variant home file
    for bt in "${base_tools[@]}"; do
        variant="${bt}-${name}"
        home=$(_profile_home_dir "$bt" "$name")
        file=$(_profile_write_variant "$bt" "$variant" "$home" "$name")
        variants+=("$variant")
        echo "    $(_green "✓") $bt → $(_cyan "$variant")  ($home/)"
        if [[ "$do_adopt" == true ]]; then
            _profile_adopt_home "$variant" "$home" "$overlay_src"
        fi
    done

    _profile_register "$name" "$overlay_rel" "${variants[@]}"

    echo ""
    _green "  Profile '$name' registered."; echo ""
    echo "    overlay:  $overlay_rel/src/   $(_dim "(drop profile-only rules/skills here)")"
    echo "    sync:     $(_cyan "agentsync sync --profile $name")"
    echo ""
}

# ── list ────────────────────────────────────────────────────────────────────

_profile_list() {
    _profile_prepare_context
    local -a names=()
    local p
    while IFS= read -r p; do [[ -n "$p" ]] && names+=("$p"); done < <(list_profiles)

    echo ""
    if [[ ${#names[@]} -eq 0 ]]; then
        _dim "  No profiles. Create one with: agentsync profile add <name>"; echo ""
        return 0
    fi
    _bold "  Profiles"; echo ""
    for p in "${names[@]}"; do
        local active_label
        active_label="$(_dim "inactive")"
        profile_is_active "$p" && active_label="$(_green "active")"
        echo "    $(_cyan "$p")  [$active_label]"
        echo "      overlay: $(profile_overlay_dir "$p")/src/"
        local t
        while IFS= read -r t; do
            [[ -z "$t" ]] && continue
            echo "      tool:    $t  →  $(get_tool_value "$t" "profile_home")/"
        done < <(profile_tools "$p")
    done
    echo ""
}

# ── remove ──────────────────────────────────────────────────────────────────

_profile_remove() {
    local name=""
    local assume_yes=false
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --yes|-y) assume_yes=true; shift ;;
            -*) echo "$(_red "Error"): unknown flag: $1" >&2; return 2 ;;
            *) if [[ -z "$name" ]]; then name="$1"; shift; else echo "$(_red "Error"): too many arguments." >&2; return 2; fi ;;
        esac
    done
    [[ -z "$name" ]] && { echo "$(_red "Error"): agentsync profile remove <name>" >&2; return 2; }

    _profile_prepare_context
    if [[ -z "$(_yaml_find_key_line "$PROJECT_CONFIG_PATH" "profiles.$name")" ]]; then
        echo "$(_red "Error"): no profile '$name' in $PROJECT_CONFIG_PATH" >&2
        return 1
    fi

    local -a variants=()
    local t
    while IFS= read -r t; do [[ -n "$t" ]] && variants+=("$t"); done < <(profile_tools "$name")

    echo ""
    _yellow "  Removing profile '$name'"; echo ""
    echo "    Deletes config-home output, variant tool files, and the profiles entry."
    echo "    Overlay sources under .ai/profiles/$name/ are kept."
    echo ""
    if [[ "$assume_yes" != true ]] && is_tty; then
        prompt_confirm "Proceed?" "n" || { echo "$(_dim "Cancelled.")"; return 0; }
    fi

    # Delete each variant's config-home output, then its variant YAML.
    local home home_abs uf
    for t in "${variants[@]+"${variants[@]}"}"; do
        home=$(get_tool_value "$t" "profile_home")
        if [[ -n "$home" ]]; then
            home_abs=$(resolve_dest_path "$home" "profile_home for $t" 2>/dev/null || echo "")
            if [[ -n "$home_abs" ]] && [[ -d "$home_abs" ]]; then
                rm -rf "$home_abs"
                echo "    $(_green "✓") removed $home/"
            fi
        fi
        uf=$(tool_resolver_user_file "$t")
        [[ -f "$uf" ]] && rm -f "$uf"
        rm -rf "$REPO_ROOT/.ai/src/tools/$t"
    done

    yaml_remove_key "$PROJECT_CONFIG_PATH" "profiles.$name"
    # Drop the now-empty `profiles:` header when the last profile is gone.
    [[ -z "$(list_profiles)" ]] && yaml_remove_key "$PROJECT_CONFIG_PATH" "profiles"
    echo ""
    _green "  Profile '$name' removed."; echo ""
}

# ── dispatch ────────────────────────────────────────────────────────────────

cmd_profile() {
    local sub="${1:-list}"
    case "$sub" in
        add)    shift; _profile_add "$@" ;;
        list|ls) shift 2>/dev/null || true; _profile_list ;;
        remove|rm) shift; _profile_remove "$@" ;;
        --help|-h|help)
            cat <<'USAGE'
Usage: agentsync profile <command>

  add <name> [--tools a,b] [--adopt]   Scaffold variant tools + overlay + config entry
  list                                 Show profiles, their tools and config homes
  remove <name> [--yes]                Delete config-home output, variants, and entry

Sync a profile:  agentsync sync --profile <name>
Active profiles also sync on a plain: agentsync sync
USAGE
            ;;
        *)
            echo "$(_red "Error"): unknown subcommand: $sub" >&2
            echo "Try: agentsync profile --help" >&2
            return 2
            ;;
    esac
}
