#!/usr/bin/env bash
# Helper to update .gitignore with generated paths
# Only touches content between specific markers

# Update .gitignore with a list of paths
# Usage: update_gitignore "path/to/.gitignore" "$(printf '%s\n' 'path1' 'path with spaces/path2')"
update_gitignore() {
    local gitignore_file="$1"
    local paths_string="$2"
    
    # Define markers
    local start_marker="# --- AI SYNC GENERATED START ---"
    local end_marker="# --- AI SYNC GENERATED END ---"
    
    # Ensure .gitignore exists
    if [[ ! -f "$gitignore_file" ]]; then
        touch "$gitignore_file"
    fi
    
    # Create the block content
    local new_block="$start_marker
# Automatically generated by .ai/system/sync.sh
# Do not edit this block manually.
"
    
    # Append paths (sorted/deduplicated). Input paths are newline-delimited.
    if [[ -n "$paths_string" ]]; then
        local sorted_paths
        sorted_paths=$(printf '%s\n' "$paths_string" | sed '/^$/d' | sort | uniq)
        new_block="${new_block}${sorted_paths}
"
    fi
    new_block="${new_block}${end_marker}"
    
    local has_start=false
    local has_end=false
    grep -qF "$start_marker" "$gitignore_file" && has_start=true
    grep -qF "$end_marker" "$gitignore_file" && has_end=true

    # Replace block only when both markers are present.
    # If markers are inconsistent, append a fresh block to avoid deleting user content.
    if [[ "$has_start" == "true" ]] && [[ "$has_end" == "true" ]]; then
        # Markers exist: replace content between them.
        # Approach:
        # 1. Read file line by line
        # 2. Print until start marker
        # 3. Print new block
        # 4. Skip lines until end marker
        # 5. Print remaining lines

        local temp_file
        temp_file="$(mktemp "${TMPDIR:-/tmp}/agent_sync_gitignore.XXXXXX")"
        local skip=0

        while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ "$line" == "$start_marker" ]]; then
                printf '%s\n' "$new_block" >> "$temp_file"
                skip=1
            elif [[ "$line" == "$end_marker" ]]; then
                skip=0
            elif [[ $skip -eq 0 ]]; then
                printf '%s\n' "$line" >> "$temp_file"
            fi
        done < "$gitignore_file"
        
        mv "$temp_file" "$gitignore_file"
        log_step "Updated .gitignore block"
        
    else
        if [[ "$has_start" == "true" ]] || [[ "$has_end" == "true" ]]; then
            log_warning "Detected inconsistent .gitignore markers. Appending a fresh generated block."
        fi

        # Markers do not exist: append to end
        printf '\n' >> "$gitignore_file"
        printf '%s\n' "$new_block" >> "$gitignore_file"
        log_step "Added generated block to .gitignore"
    fi
}
